//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQPadUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinqPadUtilResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinqPadUtilResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LINQPadUtils.LinqPadUtilResources", typeof(LinqPadUtilResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string DumpExtendedFoot {
            get {
                return ResourceManager.GetString("DumpExtendedFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;Generator&quot; content=&quot;LINQPadUtils, honey!&quot; /&gt;
        ///
        ///    &lt;style type=&apos;text/css&apos;&gt;
        ///        body {
        ///            margin: 0.3em 0.3em 0.4em 0.4em;
        ///            font-family: Verdana;
        ///            font-size: 80%;
        ///            background: white;
        ///        }
        ///
        ///        p, pre {
        ///            margin: 0;
        ///            padding: 0;
        ///            f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DumpExtendedHead {
            get {
                return ResourceManager.GetString("DumpExtendedHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/table&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string EnumerableResultTableFoot {
            get {
                return ResourceManager.GetString("EnumerableResultTableFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;spacer&quot;&gt;
        ///    &lt;table id=&quot;t{tablecount}&quot; class=&quot;{tablesorter_class}&quot;&gt;
        ///        &lt;thead&gt;
        ///            &lt;tr&gt;
        ///                &lt;td class=&quot;typeheader&quot; colspan=&quot;{colspan}&quot;&gt;
        ///                    &lt;a href=&quot;&quot; class=&quot;typeheader&quot; onclick=&quot;return toggle(&apos;t{tablecount}&apos;);&quot;&gt;
        ///                        &lt;span class=&quot;typeglyph&quot; id=&quot;t{tablecount}ud&quot;&gt;5&lt;/span&gt;{typename} ({itemcount} items)
        ///                    &lt;/a&gt;
        ///                    &lt;!--&lt;a href=&quot;&quot; class=&quot;extenser&quot; onclick=&quot;return window.external.CustomClick(&apos;0&apos;,false [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnumerableResultTableHead {
            get {
                return ResourceManager.GetString("EnumerableResultTableHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var firebug={version:[1.231,20100118],el:{},env:{&quot;css&quot;:&quot;http://getfirebug.com/releases/lite/1.2/firebug-lite.css&quot;,&quot;debug&quot;:true,&quot;detectFirebug&quot;:true,&quot;dIndex&quot;:&quot;console&quot;,&quot;height&quot;:295,&quot;hideDOMFunctions&quot;:false,&quot;openInPopup&quot;:false,&quot;override&quot;:false,&quot;ml&quot;:false,&quot;showIconWhenHidden&quot;:true,&quot;popupTop&quot;:1,&quot;popupLeft&quot;:1,&quot;popupWidth&quot;:undefined,&quot;popupHeight&quot;:undefined,&quot;textNodeChars&quot;:0},internal:{&quot;cache&quot;:{},&quot;extConsole&quot;:null,&quot;init&quot;:false,&quot;isPopup&quot;:false,&quot;liteFilename&quot;:null,&quot;minimized&quot;:false,&quot;popupWin&quot;:null,&quot;targetWindow&quot;:und [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firebug_lite_compressed {
            get {
                return ResourceManager.GetString("firebug_lite_compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.1&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_11_1_min {
            get {
                return ResourceManager.GetString("jquery_1_11_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///(function($){$.extend({tablesorter:new
        ///function(){var parsers=[],widgets=[];this.defaults={cssHeader:&quot;header&quot;,cssAsc:&quot;headerSortUp&quot;,cssDesc:&quot;headerSortDown&quot;,cssChildRow:&quot;expand-child&quot;,sortInitialOrder:&quot;asc&quot;,sortMultiSortKey:&quot;shiftKey&quot;,sortForce:null,sortAppend:null,sortLocaleCompare:true,textExtraction:&quot;simple&quot;,parsers:{},widgets:[],widgetZebra:{css:[&quot;even&quot;,&quot;odd&quot;]},headers:{},widthFixed:false,cancelSelection:true,sortList:[],headerList:[],dateFormat:&quot;us&quot;,decimal:&apos;/\.|\,/g&apos;,onRenderHeader:null,selectorHea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_tablesorter_min {
            get {
                return ResourceManager.GetString("jquery_tablesorter_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;&quot;)]
        ///[assembly: AssemblyProduct(&quot;&quot;)]
        ///[assembly: AssemblyCopyright(&quot;Copyright © [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string linqpad_assemblyinfo_2012 {
            get {
                return ResourceManager.GetString("linqpad_assemblyinfo_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;x86&lt;/Platform&gt;
        ///    &lt;ProjectGuid&gt;{289E6BC4-C22D-46A0-B9AB-F71A36DF81AD}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Exe&lt;/OutputType&gt;
        ///    &lt;RootNamespace&gt;{projname}&lt;/RootNamespace&gt;
        ///    &lt;AssemblyName&gt;{projname}&lt;/AssemblyName&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string linqpad_proj_template_2012 {
            get {
                return ResourceManager.GetString("linqpad_proj_template_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 2012
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;{slnname}&quot;, &quot;{slnname}\{slnname}.csproj&quot;, &quot;{{projguid}}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|x86 = Debug|x86
        ///		Release|x86 = Release|x86
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///		{{projguid}}.Debug|x86.ActiveCfg = Debug|x86
        ///		{{projguid}}.Debug|x86.Build.0 = Debug|x86
        ///		{{p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string linqpad_sln_template_2012 {
            get {
                return ResourceManager.GetString("linqpad_sln_template_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/table&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ObjectResultTableFoot {
            get {
                return ResourceManager.GetString("ObjectResultTableFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;spacer linqpad&quot;&gt;
        ///    &lt;table id=&quot;t{tablecount}&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;typeheader&quot; colspan=&quot;{colspan}&quot;&gt;
        ///                &lt;a href=&quot;&quot; class=&quot;typeheader&quot; onclick=&quot;return toggle(&apos;t{tablecount}&apos;);&quot;&gt;
        ///                    &lt;span class=&quot;typeglyph&quot; id=&quot;t{tablecount}ud&quot;&gt;5&lt;/span&gt;{typename}
        ///                &lt;/a&gt;
        ///                &lt;!--&lt;a href=&quot;&quot; class=&quot;extenser&quot; onclick=&quot;return window.external.CustomClick(&apos;0&apos;,false);&quot;&gt;&lt;span class=&quot;extenser&quot;&gt;4&lt;/span&gt;&lt;/a&gt;--&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///.
        /// </summary>
        internal static string ObjectResultTableHead {
            get {
                return ResourceManager.GetString("ObjectResultTableHead", resourceCulture);
            }
        }
    }
}
