//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQPadUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinqPadUtils {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinqPadUtils() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LINQPadUtils.LinqPadUtils", typeof(LinqPadUtils).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;Generator&quot; content=&quot;LINQ to XML, baby!&quot; /&gt;
        ///    &lt;style type=&apos;text/css&apos;&gt;
        ///        body {
        ///            margin: 0.3em 0.3em 0.4em 0.4em;
        ///            font-family: Verdana;
        ///            font-size: 80%;
        ///            background: white;
        ///        }
        ///
        ///        p, pre {
        ///            margin: 0;
        ///            padding: 0;
        ///            font- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DumpExtended {
            get {
                return ResourceManager.GetString("DumpExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;spacer&quot;&gt;
        ///    &lt;table id=&quot;t1&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;typeheader&quot; colspan=&quot;3&quot;&gt;
        ///                &lt;a href=&quot;&quot; class=&quot;typeheader&quot; onclick=&quot;return toggle(&apos;t1&apos;);&quot;&gt;
        ///                    &lt;span class=&quot;typeglyph&quot; id=&quot;t1ud&quot;&gt;5&lt;/span&gt;{0} ({1} items)
        ///                &lt;/a&gt;
        ///                &lt;a href=&quot;&quot; class=&quot;extenser&quot; onclick=&quot;return window.external.CustomClick(&apos;0&apos;,false);&quot;&gt;
        ///                    &lt;span class=&quot;extenser&quot;&gt;4&lt;/span&gt;
        ///                &lt;/a&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///
        ///        {3}        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResultTable {
            get {
                return ResourceManager.GetString("ResultTable", resourceCulture);
            }
        }
    }
}
